---
- name: Create a new project
  hosts: localhost
  vars:
    docker_host: "{{ lookup('env', 'DOCKER_HOST')|urlsplit('hostname') }}"
    project:
      name: "Forge"
    bitbucket_server: http://{{ docker_host}}/bitbucket
    bibucket:
      user:
        login: forge_user
        password: mdp4forge_user
  tasks:
  - name: Delete Bitbucket User
    bitbucket_user:
      server_url: "{{ bitbucket_server }}"
      validate_certs: False
      login_token: WnUzDsxjy8230-Dy_k
      username: myusername
      state: absent
    delegate_to: localhost

  - name: Create Bitbucket User
    bitbucket_user:
      server_url: "{{ bitbucket_server }}"
      validate_certs: True
      login_user: dj-wasabi
      login_password: MySecretPassword
      name: My Name
      username: myusername
      password: mysecretpassword
      email: me@example.com
      sshkey_name: MySSH
      sshkey_file: ssh-rsa AAAAB3NzaC1yc...
      state: present

  - name: "Delete Bitbucket Group"
    bitbucket_group:
      server_url: "{{ bitbucket_server }}"
      validate_certs: False
      login_token: WnUzDsxjy8230-Dy_k
      name: my_first_group
      state: absent

  - name: "Create Bitbucket Group"
    bitbucket_group:
      server_url: "{{ bitbucket_server }}"
      validate_certs: True
      login_user: dj-wasabi
      login_password: "MySecretPassword"
      name: my_first_group
      path: my_first_group
      state: present

  - name: Delete Bitbucket Project
    bitbucket_project:
      server_url: "{{ bitbucket_server }}"
      validate_certs: False
      login_token: WnUzDsxjy8230-Dy_k
      name: my_first_project
      state: absent

  - name: Create Bitbucket Project in group Ansible
    bitbucket_project:
      server_url: "{{ bitbucket_server }}"
      validate_certs: True
      login_user: dj-wasabi
      login_password: MySecretPassword
      name: my_first_project
      group: ansible
      issues_enabled: False
      wiki_enabled: True
      snippets_enabled: True
      import_url: http://git.example.com/example/lab.git
      state: present

#  - name: Import skeleton
#  - name: Create JIRA project
#  - name: Create Confluence projet
#  - name: Create Jenkins build
#  - name: Launch Jenkins build
#  - name: Check artifact has been created in Nexus
